---
- name: Create group
  become: true
  ansible.builtin.group:
    name: acme
    system: true

- name: Create user
  become: true
  ansible.builtin.user:
    name: acme
    system: true
    shell: /bin/bash
    group: acme
    password: "!"
    create_home: true
    home: /opt/acme

- name: Check if acme is installed yet
  register: acme
  ansible.builtin.stat:
    path: /opt/acme/acme.sh

- name: Create directory
  when: not acme.stat.exists
  become: true
  ansible.builtin.file:
    path: /opt/acme
    owner: acme
    group: acme
    mode: "0775"
    state: directory

- name: Download acme.sh
  become: true
  when: not acme.stat.exists
  ansible.builtin.git:
    repo: https://github.com/acmesh-official/acme.sh.git
    dest: /tmp/acme
    depth: 1
    version: "{{ acme_version }}"

- name: Install acme.sh
  become: true
  become_user: acme
  changed_when: true
  when: not acme.stat.exists
  ansible.builtin.command:
    argv:
      - ./acme.sh
      - --install
      - --home
      - /opt/acme
      - --config-home
      - /opt/acme/config
      - --cert-home
      - /opt/acme/certs
      - --nocron
  args:
    chdir: /tmp/acme

- name: Set PDNS & discord config
  become: true
  become_user: acme
  ansible.builtin.blockinfile:
    backup: true
    dest: /opt/acme/config/account.conf
    block: |
      PDNS_Url='{{ apis.pdns }}'
      PDNS_ServerId='localhost'
      PDNS_Token='{{ acme_pdns_token }}'
      DEFAULT_ACME_SERVER='{{ apis.vault }}/{{ acme_acme_dir }}'
      SAVED_DISCORD_WEBHOOK_URL="{{ acme_discord_webhook_url }}"
      NOTIFY_HOOK='discord'

- name: Check for account config
  register: acme_account
  become: true
  ansible.builtin.stat:
    path: "/opt/acme/config/ca/vault.{{ ansible_facts['ansible_domain'] }}/v1/{{ acme_pki_engine }}/roles/{{ acme_pki_role }}/acme/directory/account.json"

- name: Get new EAB keys from vault
  delegate_to: localhost
  become: false
  register: eab_info
  when: not acme_account.stat.exists
  community.hashi_vault.vault_write:
    path: "{{ acme_pki_engine }}/roles/{{ acme_pki_role }}/acme/new-eab"

- name: Register account
  become: true
  become_user: acme
  changed_when: true
  when: not acme_account.stat.exists
  ansible.builtin.command:
    argv:
      - /opt/acme/acme.sh
      - --config-home
      - /opt/acme/config
      - --register-account
      - --eab-kid
      - "{{ eab_info.data.data.id }}"
      - --eab-hmac-key
      - "{{ eab_info.data.data.key }}"

- name: Register acme service
  become: true
  notify: Daemon-reload
  ansible.builtin.copy:
    dest: /etc/systemd/system/acme.service
    owner: root
    group: root
    mode: "0640"
    content: |
      [Unit]
      Description=Renew Let's Encrypt certificates using acme.sh
      After=network-online.target

      [Service]
      Type=oneshot
      User=acme
      Group=acme
      # --home's argument should be where the acme.sh script resides.
      ExecStart=/opt/acme/acme.sh --cron --home /opt/acme --config-home /opt/acme/config

- name: Register acme timer
  become: true
  notify: Start-acme-timer
  ansible.builtin.copy:
    dest: /etc/systemd/system/acme.timer
    owner: root
    group: root
    mode: "0640"
    content: |
      [Unit]
      Description=Daily renewal of Let's Encrypt's certificates

      [Timer]
      OnBootSec=15min
      OnUnitActiveSec=8h
      Persistent=true

      [Install]
      WantedBy=timers.target
