---
- name: daemon-reload
  ansible.builtin.systemd_service:
    daemon-reload: true
  become: true

- name: start-acme-timer
  ansible.builtin.systemd_service:
    name: acme.timer
    state: started
    enabled: true
    daemon-reload: true
  become: true
